# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientstreaming.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63lientstreaming.proto\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\x01\x32>\n\x0f\x43lientStreaming\x12+\n\x11GetServerResponse\x12\x08.Message\x1a\x08.Message\"\x00(\x01\x62\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'clientstreaming_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)

_CLIENTSTREAMING = DESCRIPTOR.services_by_name['ClientStreaming']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=25
  _MESSAGE._serialized_end=51
  _CLIENTSTREAMING._serialized_start=53
  _CLIENTSTREAMING._serialized_end=115
# @@protoc_insertion_point(module_scope)
