# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x02pb\"\x18\n\tMyMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t22\n\x04\x45\x63ho\x12*\n\x08SendEcho\x12\r.pb.MyMessage\x1a\r.pb.MyMessage\"\x00\x42\x06Z\x04./pbb\x06proto3')



_MYMESSAGE = DESCRIPTOR.message_types_by_name['MyMessage']
MyMessage = _reflection.GeneratedProtocolMessageType('MyMessage', (_message.Message,), {
  'DESCRIPTOR' : _MYMESSAGE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:pb.MyMessage)
  })
_sym_db.RegisterMessage(MyMessage)

_ECHO = DESCRIPTOR.services_by_name['Echo']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _MYMESSAGE._serialized_start=21
  _MYMESSAGE._serialized_end=45
  _ECHO._serialized_start=47
  _ECHO._serialized_end=97
# @@protoc_insertion_point(module_scope)
