package grpcgenerated;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple.proto

public interface RootResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcgenerated.RootResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double root = 1;</code>
   * @return The root.
   */
  double getRoot();
}
