package grpcgenerated;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple.proto

public interface RootRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpcgenerated.RootRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   * @return The number.
   */
  int getNumber();
}
