package grpcgenerated;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple.proto

public final class Simple {
  private Simple() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RootRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RootRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RootResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RootResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014simple.proto\"\035\n\013RootRequest\022\016\n\006number\030" +
      "\001 \001(\005\"\034\n\014RootResponse\022\014\n\004root\030\001 \001(\00122\n\013R" +
      "ootService\022#\n\004root\022\014.grpcgenerated.RootRequest\032\r.RootR" +
      "esponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RootRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RootRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RootRequest_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_RootResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RootResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RootResponse_descriptor,
        new java.lang.String[] { "Root", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
