# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\x01\x32>\n\rBidirectional\x12-\n\x11GetServerResponse\x12\x08.Message\x1a\x08.Message\"\x00(\x01\x30\x01\x32>\n\x0fServerStreaming\x12+\n\x11GetServerResponse\x12\x08.Message\x1a\x08.Message\"\x00\x30\x01\x32>\n\x0f\x43lientStreaming\x12+\n\x11GetServerResponse\x12\x08.Message\x1a\x08.Message\"\x00(\x01\x32\x32\n\x05Unary\x12)\n\x11GetServerResponse\x12\x08.Message\x1a\x08.Message\"\x00\x62\x06proto3')



_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)

_BIDIRECTIONAL = DESCRIPTOR.services_by_name['Bidirectional']
_SERVERSTREAMING = DESCRIPTOR.services_by_name['ServerStreaming']
_CLIENTSTREAMING = DESCRIPTOR.services_by_name['ClientStreaming']
_UNARY = DESCRIPTOR.services_by_name['Unary']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=17
  _MESSAGE._serialized_end=43
  _BIDIRECTIONAL._serialized_start=45
  _BIDIRECTIONAL._serialized_end=107
  _SERVERSTREAMING._serialized_start=109
  _SERVERSTREAMING._serialized_end=171
  _CLIENTSTREAMING._serialized_start=173
  _CLIENTSTREAMING._serialized_end=235
  _UNARY._serialized_start=237
  _UNARY._serialized_end=287
# @@protoc_insertion_point(module_scope)
