# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: unary.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bunary.proto\"\x1d\n\x0bRootRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1c\n\x0cRootResponse\x12\x0c\n\x04root\x18\x01 \x01(\x01\x32\x34\n\x0bRootService\x12%\n\x04root\x12\x0c.RootRequest\x1a\r.RootResponse\"\x00\x62\x06proto3')



_ROOTREQUEST = DESCRIPTOR.message_types_by_name['RootRequest']
_ROOTRESPONSE = DESCRIPTOR.message_types_by_name['RootResponse']
RootRequest = _reflection.GeneratedProtocolMessageType('RootRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROOTREQUEST,
  '__module__' : 'unary_pb2'
  # @@protoc_insertion_point(class_scope:RootRequest)
  })
_sym_db.RegisterMessage(RootRequest)

RootResponse = _reflection.GeneratedProtocolMessageType('RootResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROOTRESPONSE,
  '__module__' : 'unary_pb2'
  # @@protoc_insertion_point(class_scope:RootResponse)
  })
_sym_db.RegisterMessage(RootResponse)

_ROOTSERVICE = DESCRIPTOR.services_by_name['RootService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROOTREQUEST._serialized_start=15
  _ROOTREQUEST._serialized_end=44
  _ROOTRESPONSE._serialized_start=46
  _ROOTRESPONSE._serialized_end=74
  _ROOTSERVICE._serialized_start=76
  _ROOTSERVICE._serialized_end=128
# @@protoc_insertion_point(module_scope)
